# Metadata about the site
name: Cidney's Site
title: cidney.org
author: Cidney Hamilton
email: cidney@cidneyhamilton.com
description: This is Cidney Hamilton's personal website and home on the Internet. I talk about game development, tabletop RPGs, Emacs, and more.
url: https://cidney.org
source-url: https://github.com/cidneyhamilton/cidney.org

# Social Links

fedi-url: https://social.cidney.org/@cidney
itch-url: https://cidney.itch.io
github-url: https://github.com/cidneyhamilton
gitlab-url: https://gitlab.com/cidney
facebook-url: https://facebook.com/cidneydev

# Icons 
favicon: "/assets/images/favicon.ico"
apple-touch-icon: "/assets/images/favicons/apple-touch-icon.png"
featured-image: "/assets/images/default-image.png"

# CSS
font-awesome: "/assets/font-awesome/css/fork-awesome.min.css"
css-link: "/assets/css/style.css"

# Webmentions
# webmentions:
#  username: cidney.org

# Build settings

plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-archives
    
exclude:
  - README.md
  - Rakefile
  - Gemfile
  - Gemfile.lock

jekyll-archives:
  enabled:
    - categories
  layout: category
  permalinks:
    year: '/:year/'
    month: '/:year/:month/'
    day: '/:year/:month/:day/'
    tag: '/tag/:name/'
    category: '/category/:name/'
