# Metadata about the site
name: Cidney Hamilton
title: cidney.org
author: Cidney Hamilton
email: cidney@cidneyhamilton.com
description: Software engineer turned indie game dev. American living in Berlin. This is my personal website.
url: https://cidney.org
source-url: https://github.com/cidneyhamilton/cidney.org

# Social Links

fedi-url: https://social.city-of-glass.net/@cidney
itch-url: https://cidney.itch.io
github-url: https://github.com/cidneyhamilton
gitlab-url: https://gitlab.com/cidney
facebook-url: https://facebook.com/cidneydev

# Icons 
favicon: "/assets/images/favicon.ico"
apple-touch-icon: "/assets/images/favicons/apple-touch-icon.png"

# CSS
font-awesome: "/assets/font-awesome/css/fork-awesome.min.css"
css-link: "/assets/css/style.css"

# Build settings

plugins:
  - jekyll-feed
  - jekyll-redirect-from

exclude:
  - README.md
  - Rakefile
  - Gemfile
  - Gemfile.lock

